# Development ready docker-compose file

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP server

volumes:
  postgres-data:
  redis-data:
