default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: silent-dose_development

test:
  <<: *default
  database: silent-dose_test

production:
  <<: *default
  database: silent-dose_production
